export type Category = 'clothes' | 'furniture' | 'books' | 'electronics' | 'toys' | 'other';

export type ItemStatus = 'available' | 'claimed';

export interface DonationItem {
  id: string;
  name: string;
  description: string;
  category: Category;
  image: string;
  location: string;
  pincode: string;
  donorName: string;
  whatsappNumber: string;
  timePosted: string;
  status: ItemStatus;
  claimedBy?: string;
}

export const categoryLabels: Record<Category, string> = {
  clothes: '👕 Kapde',
  furniture: '🪑 Furniture',
  books: '📚 Kitaabein',
  electronics: '📱 Electronics',
  toys: '🧸 Khilone',
  other: '📦 Other',
};

export const categoryColors: Record<Category, string> = {
  clothes: 'bg-tag-clothes text-foreground',
  furniture: 'bg-tag-furniture text-foreground',
  books: 'bg-tag-books text-foreground',
  electronics: 'bg-tag-electronics text-foreground',
  toys: 'bg-tag-toys text-foreground',
  other: 'bg-tag-other text-foreground',
};

export const filterCategories: { value: Category | 'all'; label: string }[] = [
  { value: 'all', label: '🔥 Sab' },
  { value: 'clothes', label: '👕 Kapde' },
  { value: 'furniture', label: '🪑 Furniture' },
  { value: 'books', label: '📚 Books' },
  { value: 'electronics', label: '📱 Electronics' },
  { value: 'toys', label: '🧸 Toys' },
  { value: 'other', label: '📦 Other' },
];

export const sampleItems: DonationItem[] = [
  {
    id: '1',
    name: 'Wooden Study Table',
    description: 'Solid wood study table in great condition. Perfect for students. Minor scratches but very sturdy. Used for 2 years. Legs are all intact.',
    category: 'furniture',
    image: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=400&h=300&fit=crop',
    location: 'Andheri West, Mumbai',
    pincode: '400058',
    donorName: 'Rahul S.',
    whatsappNumber: '919876543210',
    timePosted: '2 ghante pehle',
    status: 'available',
  },
  {
    id: '2',
    name: 'Kids Winter Jacket (Age 4-6)',
    description: 'Warm winter jacket for kids, hardly worn. Bright red color, perfect for chilly winters. Washed and ready to give away.',
    category: 'clothes',
    image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=400&h=300&fit=crop',
    location: 'Koramangala, Bangalore',
    pincode: '560034',
    donorName: 'Priya M.',
    whatsappNumber: '919876543211',
    timePosted: '5 ghante pehle',
    status: 'claimed',
    claimedBy: 'Anita V.',
  },
  {
    id: '3',
    name: 'NCERT Books Class 10 (Full Set)',
    description: 'Complete set of NCERT textbooks for Class 10. All subjects included. Some highlighting inside but all pages intact. Best for students who need them.',
    category: 'books',
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&h=300&fit=crop',
    location: 'Dwarka, Delhi',
    pincode: '110075',
    donorName: 'Amit K.',
    whatsappNumber: '919876543212',
    timePosted: '1 din pehle',
    status: 'available',
  },
  {
    id: '4',
    name: 'Samsung Galaxy J7 (Working)',
    description: 'Old Samsung J7 in working condition. Battery holds charge for about 4-5 hours. Screen has a small crack on the corner but touch works fine.',
    category: 'electronics',
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=300&fit=crop',
    location: 'Salt Lake, Kolkata',
    pincode: '700091',
    donorName: 'Suman D.',
    whatsappNumber: '919876543213',
    timePosted: '3 ghante pehle',
    status: 'claimed',
    claimedBy: 'Ravi T.',
  },
  {
    id: '5',
    name: 'Teddy Bear (Large)',
    description: 'Large fluffy teddy bear, about 3 feet tall. Clean and in excellent condition. My daughter has outgrown it. Would make some child very happy! 🧸',
    category: 'toys',
    image: 'https://images.unsplash.com/photo-1559715541-5daf8a0296d0?w=400&h=300&fit=crop',
    location: 'Baner, Pune',
    pincode: '411045',
    donorName: 'Neha R.',
    whatsappNumber: '919876543214',
    timePosted: '6 ghante pehle',
    status: 'available',
  },
  {
    id: '6',
    name: 'Pressure Cooker 5L',
    description: 'Prestige pressure cooker, 5 litre capacity. Works perfectly, just bought a new one. Gasket is new. Comes with lid and whistle.',
    category: 'other',
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=300&fit=crop',
    location: 'Vastrapur, Ahmedabad',
    pincode: '380015',
    donorName: 'Kiran P.',
    whatsappNumber: '919876543215',
    timePosted: '30 min pehle',
    status: 'available',
  },
  {
    id: '7',
    name: 'Dumbells Set 5kg',
    description: 'Pair of 5kg dumbbells with stand. Used for 3 months but in perfect condition. Ideal for home gym setup.',
    category: 'other',
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&h=300&fit=crop',
    location: 'Malviya Nagar, Delhi',
    pincode: '110017',
    donorName: 'Vikram S.',
    whatsappNumber: '919876543216',
    timePosted: '4 ghante pehle',
    status: 'available',
  },
  {
    id: '8',
    name: 'Cotton Saree Collection',
    description: 'Pack of 3 beautiful cotton sarees in traditional designs. Perfect condition, worn only for special occasions. Great quality fabric.',
    category: 'clothes',
    image: 'https://images.unsplash.com/photo-1608631297005-0c6688d566c4?w=400&h=300&fit=crop',
    location: 'T.Nagar, Chennai',
    pincode: '600017',
    donorName: 'Lakshmi V.',
    whatsappNumber: '919876543217',
    timePosted: '2 din pehle',
    status: 'available',
  },
  {
    id: '9',
    name: 'Wooden Bookshelf',
    description: 'Beautiful wooden bookshelf with 5 shelves. Solid wood construction. Minor dust marks but structurally very strong. Great for organizing books.',
    category: 'furniture',
    image: 'https://images.unsplash.com/photo-1571275139221-5c1aa93f2f16?w=400&h=300&fit=crop',
    location: 'Sector 12, Noida',
    pincode: '201301',
    donorName: 'Arun K.',
    whatsappNumber: '919876543218',
    timePosted: '8 ghante pehle',
    status: 'claimed',
    claimedBy: 'Anjali M.',
  },
  {
    id: '10',
    name: 'Harry Potter Series (Full Set)',
    description: 'Complete Harry Potter series - all 7 books. First edition copies, excellent condition. Must read classics!',
    category: 'books',
    image: 'https://images.unsplash.com/photo-1507842217343-583f20270319?w=400&h=300&fit=crop',
    location: 'Indiranagar, Bangalore',
    pincode: '560038',
    donorName: 'Shreya C.',
    whatsappNumber: '919876543219',
    timePosted: '12 ghante pehle',
    status: 'available',
  },
  {
    id: '11',
    name: 'Laptop Stand + USB Hub',
    description: 'Adjustable laptop stand with built-in USB hub. Perfect for working from home. Aluminum construction, very sturdy.',
    category: 'electronics',
    image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400&h=300&fit=crop',
    location: 'Whitefield, Bangalore',
    pincode: '560066',
    donorName: 'Nitin R.',
    whatsappNumber: '919876543220',
    timePosted: '5 ghante pehle',
    status: 'available',
  },
  {
    id: '12',
    name: 'Roller Skates (Size 6)',
    description: 'Adjustable roller skates, size 6. Smooth gliding wheels, full protective gear included. Perfect for beginners!',
    category: 'toys',
    image: 'https://images.unsplash.com/photo-1599572929559-c924f2e8f31e?w=400&h=300&fit=crop',
    location: 'Vile Parle, Mumbai',
    pincode: '400056',
    donorName: 'Ravi T.',
    whatsappNumber: '919876543221',
    timePosted: '3 din pehle',
    status: 'available',
  },
  {
    id: '13',
    name: 'Non-Stick Cookware Set',
    description: '6-piece non-stick cookware set. Frying pan, saucepan, wok with lids. Very lightly used. High quality coating.',
    category: 'other',
    image: 'https://images.unsplash.com/photo-1589985643453-5802d6c2b7c9?w=400&h=300&fit=crop',
    location: 'Kala Niketan, Jaipur',
    pincode: '302004',
    donorName: 'Divya M.',
    whatsappNumber: '919876543222',
    timePosted: '1 din pehle',
    status: 'claimed',
    claimedBy: 'Priya K.',
  },
  {
    id: '14',
    name: 'Formal Shirts Bundle',
    description: 'Pack of 5 formal cotton shirts in different colors. Size M, excellent condition. Ideal for office wear.',
    category: 'clothes',
    image: 'https://images.unsplash.com/photo-1596631286016-b57a0672b249?w=400&h=300&fit=crop',
    location: 'Marine Drive, Mumbai',
    pincode: '400020',
    donorName: 'Akshay P.',
    whatsappNumber: '919876543223',
    timePosted: '6 ghante pehle',
    status: 'available',
  },
  {
    id: '15',
    name: 'Dining Table (4 seater)',
    description: 'Solid wood dining table with 4 chairs. Elegant design, perfect for small families. Well-maintained condition.',
    category: 'furniture',
    image: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=400&h=300&fit=crop',
    location: 'South Extension, Delhi',
    pincode: '110049',
    donorName: 'Mrs. Sharma',
    whatsappNumber: '919876543224',
    timePosted: '7 ghante pehle',
    status: 'available',
  },
  {
    id: '16',
    name: 'Self-Help Books Collection',
    description: 'Collection of 8 best-selling self-help books including "Atomic Habits" and "The Lean Startup". Great reads!',
    category: 'books',
    image: 'https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?w=400&h=300&fit=crop',
    location: 'Kalyan East, Mumbai',
    pincode: '421306',
    donorName: 'Suresh D.',
    whatsappNumber: '919876543225',
    timePosted: '2 ghante pehle',
    status: 'available',
  },
  {
    id: '17',
    name: 'Wireless Headphones',
    description: 'Bluetooth headphones with excellent sound quality. Battery lasts 20+ hours. Minor wear but works perfectly.',
    category: 'electronics',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=300&fit=crop',
    location: 'Greater Noida, UP',
    pincode: '201310',
    donorName: 'Harsh M.',
    whatsappNumber: '919876543226',
    timePosted: '9 ghante pehle',
    status: 'available',
  },
  {
    id: '18',
    name: 'LEGO Building Sets',
    description: 'Bundle of 3 LEGO sets - City, Creator, and Technic series. All pieces included, sorted and organized.',
    category: 'toys',
    image: 'https://images.unsplash.com/photo-1594787318286-3d835c1ca2e2?w=400&h=300&fit=crop',
    location: 'Thane West, Mumbai',
    pincode: '400601',
    donorName: 'Meera S.',
    whatsappNumber: '919876543227',
    timePosted: '11 ghante pehle',
    status: 'available',
  },
];

// Sample data for "My Items" tabs
export const myGivenItems: DonationItem[] = [
  sampleItems[0],
  { ...sampleItems[1], donorName: 'You' },
  sampleItems[5],
];

export const myReceivedItems: DonationItem[] = [
  { ...sampleItems[3], status: 'claimed', claimedBy: 'You' },
];
