/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PostItemRouteImport } from './routes/post-item'
import { Route as MyItemsRouteImport } from './routes/my-items'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ItemsItemIdRouteImport } from './routes/items.$itemId'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PostItemRoute = PostItemRouteImport.update({
  id: '/post-item',
  path: '/post-item',
  getParentRoute: () => rootRouteImport,
} as any)
const MyItemsRoute = MyItemsRouteImport.update({
  id: '/my-items',
  path: '/my-items',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsItemIdRoute = ItemsItemIdRouteImport.update({
  id: '/items/$itemId',
  path: '/items/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/my-items': typeof MyItemsRoute
  '/post-item': typeof PostItemRoute
  '/profile': typeof ProfileRoute
  '/support': typeof SupportRoute
  '/items/$itemId': typeof ItemsItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/my-items': typeof MyItemsRoute
  '/post-item': typeof PostItemRoute
  '/profile': typeof ProfileRoute
  '/support': typeof SupportRoute
  '/items/$itemId': typeof ItemsItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/my-items': typeof MyItemsRoute
  '/post-item': typeof PostItemRoute
  '/profile': typeof ProfileRoute
  '/support': typeof SupportRoute
  '/items/$itemId': typeof ItemsItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/my-items'
    | '/post-item'
    | '/profile'
    | '/support'
    | '/items/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/my-items'
    | '/post-item'
    | '/profile'
    | '/support'
    | '/items/$itemId'
  id:
    | '__root__'
    | '/'
    | '/my-items'
    | '/post-item'
    | '/profile'
    | '/support'
    | '/items/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MyItemsRoute: typeof MyItemsRoute
  PostItemRoute: typeof PostItemRoute
  ProfileRoute: typeof ProfileRoute
  SupportRoute: typeof SupportRoute
  ItemsItemIdRoute: typeof ItemsItemIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-item': {
      id: '/post-item'
      path: '/post-item'
      fullPath: '/post-item'
      preLoaderRoute: typeof PostItemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-items': {
      id: '/my-items'
      path: '/my-items'
      fullPath: '/my-items'
      preLoaderRoute: typeof MyItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/$itemId': {
      id: '/items/$itemId'
      path: '/items/$itemId'
      fullPath: '/items/$itemId'
      preLoaderRoute: typeof ItemsItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MyItemsRoute: MyItemsRoute,
  PostItemRoute: PostItemRoute,
  ProfileRoute: ProfileRoute,
  SupportRoute: SupportRoute,
  ItemsItemIdRoute: ItemsItemIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
